### ISSUE TITLE
Convert 2011 county-level special election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ga#1]
Using the following files:

- [ ] [October 18, 2011 runoff in Cobb](http://sos.ga.gov/elections/election_results/2011_1018/swall.htm)
- [ ] [September 20, 2011 special in Cobb](http://sos.ga.gov/elections/election_results/2011_0920/swall.htm)
- [ ] [August 16, 2011 special runoff](http://sos.ga.gov/elections/election_results/2011_0816/00426.htm)
- [ ] [July 19, 2011 specials](http://sos.ga.gov/elections/election_results/2011_0719/swall.htm)
- [ ] [June 21, 2011 special](http://sos.ga.gov/elections/election_results/2011_0621/00613.htm)

Create individual CSV files for each special election date (which may involve multiple races) using the [file name conventions](http://docs.openelections.net/archive-standardization/). The CSV files should have the following headers: `county`, `office`, `district`, `party`, `candidate`, `votes`. For offices, follow [our naming conventions](http://docs.openelections.net/archive-standardization/#office-names).

These special election files have overall results on the first page (with full candidate names) and county-specific results on interior pages, so we'll need both for our CSVs - the first page for candidate names and the interior ones for county-specific vote totals.

**Comment by mjn298** [comment]
@dwillis I'd like to help but I'm not quite sure how - I could write some HTML parsing scripts using BeautifulSoup but I don't know if that fits the way you do things - basically I'm not sure if just CSVs are desired or the scripts used as well. Any guidance would be helpful.

**Comment by dwillis** [comment]
@mjn298: we don't need the scripts, but if they could be generalizable to other GA specials that would be useful. But CSVs most important.

**Comment by Mocker9000** [comment]
Working on this one.  For the Party name I plan to spell out the names (per the convention displayed at http://docs.openelections.net/data-entry/ ), but I want to point out that the existing Georgia data here in the Github repository has a discrepancy in the party format: the 2010 files have "D" & "R", while 2011 has the party name spelled out as "Republican" and "Democrat".  Easy enough to fix either way, but unless told otherwise I'll spell it out.

**Comment by dwillis** [comment]
You can spell the party names out if you like, but at this point we'll take either way.
