### ISSUE TITLE
Uniform format of csv files for older election results?

### ISSUE THREAD

**Issue by bitmingw** [openelections/openelections-data-ga#10]
I have noticed that older years' data have multiple format, especially those special elections.

For example, in http://sos.ga.gov/elections/election_results/2002_0212/ we have candidates grouped by counties. In another election http://sos.ga.gov/elections/election_results/2001_1106/ , we have candidates grouped by districts and followed by their percentage. I would like to know if we can construct a unique format that defines the number of variables for those special elections. For those variables not shown in the election results just left them as blank.

Any suggestion is welcome!

**Comment by dwillis** [comment]
I think that sounds fine, although I'd love to see an example of the formats in action.

**Comment by ATLJoeReed** [comment]
I going to close this issue as I don't see that it's needed at this time. If anybody feels different please reopen.
