### ISSUE TITLE
2002 Special election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ga#19]
These are county-level files, using [these headers](https://gist.github.com/dwillis/f2e015d84e1eeb87d9d864e2186f8f11). Convert the data in the following urls, using the file names provided:

- [x] [20021022__ga__special__general.csv](http://sos.ga.gov/elections/election_results/2002_1022/)
- [x] [20020226__ga__special__general.csv](http://sos.ga.gov/elections/election_results/2002_0226/)
- [x] [20020212__ga__special__general.csv](http://sos.ga.gov/elections/election_results/2002_0212/)
- [x] [20020212__ga__special__general__runoff.csv](http://sos.ga.gov/elections/election_results/2002_0122/) - House 16 only
- [x] [20020122__ga__special__general.csv](http://sos.ga.gov/elections/election_results/2002_0122/) - House 16 only

**Comment by ATLJoeReed** [comment]
Hey Derek - I have these completed along with a couple of other ones. I'll submit them later tonight. Thanks

**Comment by dwillis** [comment]
+1

**Comment by hellowyousuf** [comment]
Please ignore if this makes no sense. Trying to learn data journalism :). Will greatly appreciate any feedback.

[Yousuf-2002 Special Election .Results.xlsx.zip](https://github.com/openelections/openelections-data-ga/files/257695/Yousuf-2002.Special.Election.Results.xlsx.zip)

**Comment by dwillis** [comment]
Hey @hellowyousuf, thanks! We got files for these elections submitted last night by @ATLJoeReed, but I appreciate the effort. If you'd like to give another election a try, let me know and we'll get you hooked up with something.

**Comment by hellowyousuf** [comment]
@dwillis, thanks for your kind reply. I would love to work with elections data. I will appreciate opportunities to contribute to other data projects as well. Thank you.
