### ISSUE TITLE
Convert 2012 county-level special election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ga#3]
Using the following files:

- [x] [January 3, 2012 special runoff](http://sos.ga.gov/elections/election_results/2012_0103/00568.htm)
- [x] [February 7, 2012 special](http://sos.ga.gov/elections/election_results/2012_0207/)
- [x] [March 6, 2012 special runoff](http://sos.ga.gov/elections/election_results/2012_0306/00607.htm)

Create individual CSV files for each special election date (which may involve multiple races) using the [file name conventions](http://docs.openelections.net/archive-standardization/). The CSV files should have the following headers: `county`, `office`, `district`, `party`, `candidate`, `votes`. For offices, follow [our naming conventions](http://docs.openelections.net/archive-standardization/#office-names).

These special election files have overall results on the first page (with full candidate names) and county-specific results on interior pages, so we'll need both for our CSVs - the first page for candidate names and the interior ones for county-specific vote totals.

**Comment by Joeventures** [comment]
Working on this one...

**Comment by ATLJoeReed** [comment]
I'm starting this task. Hey Derek @dwillis Luigi from Code for Atlanta has this as a project for us to work on so we should get these issue taken care of over the next few days. If you have more items we can do please post them like these and we will work with you to get Georgia complete.

**Comment by dwillis** [comment]
That's awesome - please thank Luigi for me! I'll rustle up some more tasks. I've got some work on a county-level results scraper that I need to commit.
