### ISSUE TITLE
Convert 2016 presidential primary results by congressional district

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ga#31]
Ga. secretary of state has produced two PDFs that can be converted into CSVs:

- [ ] [Republican](http://sos.ga.gov/admin/uploads/PPP_Results_by_Congressional_District_(Republican)2.pdf)
- [ ] [Democratic](http://sos.ga.gov/admin/uploads/PPP_Congressional_Totals_(Democrat)1.pdf)

**Comment by greencracker** [comment]
How does this work?  I just put it in Cometdocs and put csv here?

**Comment by greencracker** [comment]
They might have what you need already, albeit in .xls
go to Sos election results & click on the "reports" tab: http://results.enr.clarityelections.com/GA/58980/163369/en/summary.html

**Comment by dwillis** [comment]
@greencracker That would be great, and if you wanted to do some cleaning up, our CSVs have headers that look [like this file](https://github.com/openelections/openelections-data-ga/blob/master/2012/20120207__ga__special__general__state_house.csv). Our process is one candidate result in one jurisdiction per row. Ideally, you'd produce a single CSV for each file that had one candidate result per row, with the `office` of President and `district` being the district number.

**Comment by dwillis** [comment]
@greencracker right - that's for county and precinct level. these PDFs are specifically for congressional district-level breakdowns.

**Comment by greencracker** [comment]
ah I see, yea.  need the Congressional District breakdown.  So ... just make it tabular format.  I'll run em thru cometdocs.  I have a sympathy for anyone trying to get machine readable documents in this state.

**Comment by dwillis** [comment]
Thanks, @greencracker! You can fork the repo and create a pull request or just send the finished files to openelections@gmail.com.

**Comment by greencracker** [comment]
Well I'm not sure I did the pull request right but the files are here

https://github.com/greencracker/openelections-data-ga/blob/df80cc768c5f0ce9d891d9af4a3dc06a6e9fa898/20160301__ga__primary__republican_president.csv

https://github.com/greencracker/openelections-data-ga/blob/df80cc768c5f0ce9d891d9af4a3dc06a6e9fa898/20160301__ga__primary_democratic_president.csv

**Comment by dwillis** [comment]
You're very close - just go here: https://github.com/openelections/openelections-data-ga/pulls

and click on "New pull request" and fill in the details.

Thanks!
