### ISSUE TITLE
Convert 2010 special election county-level results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ga#4]
Using the following files:

- [ ] [June 8, 2010 special runoff](http://sos.ga.gov/elections/election_results/2010_0608/00309.htm)
- [ ] [May 11, 2010 special](http://sos.ga.gov/elections/election_results/2010_0511/)
- [ ] [February 23, 2010 special](http://sos.ga.gov/elections/election_results/2010_0223/swall.htm)
- [ ] [February 2, 2010 special runoff](http://sos.ga.gov/elections/election_results/2010_0202/swall.htm)
- [ ] [January 5, 2010 special](http://sos.ga.gov/elections/election_results/2010_0105/swall.htm)

Create individual CSV files for each special election date (which may involve multiple races) using the [file name conventions](http://docs.openelections.net/archive-standardization/). The CSV files should have the following headers: `county`, `office`, `district`, `party`, `candidate`, `votes`. For offices, follow [our naming conventions](http://docs.openelections.net/archive-standardization/#office-names).

These special election files have overall results on the first page (with full candidate names) and county-specific results on interior pages, so we'll need both for our CSVs - the first page for candidate names and the interior ones for county-specific vote totals.

**Comment by Joeventures** [comment]
Working on this one...

**Comment by dwillis** [comment]
Awesome, thank you! Don't hesitate to ask anything.

**Comment by Joeventures** [comment]
Sure thing, @dwillis. Do you want first names in the `candidate` column?

**Comment by dwillis** [comment]
Ideally, yes, but I've done some work on this and realize it can be a pain.
