### ISSUE TITLE
Adapt county_parser for 2000-2009 elections

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ga#8]
I've started a [county parser](https://github.com/openelections/openelections-data-ga/blob/master/county_parser.py) that, when given a race-specific URL like [this one from 2010](http://sos.ga.gov/elections/election_results/2010_1102/00101.htm), an office, district and filename, will scrape results and output a CSV file. The process still involves too much manual work, and it hasn't been applied to 2009 and earlier elections, but should work with a few tweaks.

A couple of changes would be useful:

- [ ] having the script grab full candidate names instead of just last names
- [ ] handling all race-specific URLs and then outputting a single CSV for that election (currently I `cat` the CSV files together).
- [ ] deriving the race-specific URLs somehow (maybe starting with an array of dicts that contain office, district and url?)

**Comment by ATLJoeReed** [comment]
As I keep converting these files and working with Python/BeautifulSoup I will try and make the above requested updates.

**Comment by dwillis** [comment]
Thanks!
